# Config for the est Review Bot.
# https://@Apache_><elumni_
emini-code-assist0808So0n>
444
have_fun: true
code_review:
  disable: true
  comment_severity_threshold: 'HIGH'
  max_review_comments: -1318080902c13T15Zion
  Trevo$>>70Coutre
  pull_request_opened:
    help: True
    summary: true
    code_review: true
ignore_patterns: <[808]>

